Repository WaitherTeam/Waither-BE, pull requests merged in 2024-07, with the labels that each got.

#136 ♻️ refactor: main api 로직 변경
  weather-service/src/main/java/com/waither/weatherservice/service/WeatherService.java
Labels: refactor

#157 🐛 fix: 로그인 에러처리 에러
  user-service/src/main/java/com/waither/userservice/config/WebMvcConfig.java
  user-service/src/main/java/com/waither/userservice/controller/UserController.java
  user-service/src/main/java/com/waither/userservice/global/jwt/userdetails/PrincipalDetailsService.java
  user-service/src/main/java/com/waither/userservice/global/response/ErrorCode.java
Labels: fix

#166 ✨ feature: Weather-Service로 부터 해당 시각의 체감 온도 받아오는 메서드 작성 (#165)
  user-service/src/main/java/com/waither/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/waither/userservice/converter/SurveyConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/SurveyReqDto.java
  user-service/src/main/java/com/waither/userservice/entity/UserMedian.java
  user-service/src/main/java/com/waither/userservice/global/jwt/filter/JwtAuthorizationFilter.java
  user-service/src/main/java/com/waither/userservice/global/jwt/filter/JwtLogoutFilter.java
  user-service/src/main/java/com/waither/userservice/global/jwt/util/JwtUtil.java
  user-service/src/main/java/com/waither/userservice/service/commandService/SurveyService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/UserService.java
  user-service/src/main/java/com/waither/userservice/util/CalculateUtil.java
  user-service/src/main/java/com/waither/userservice/util/RedisUtil.java
  user-service/src/main/java/com/waither/userservice/util/RestClient.java
Labels: feat
