Repository WaitherTeam/Waither-BE, pull requests merged in 2024-04, with the labels that each got.

#22 ✅ test: Kafka Test Case 작성 (#18)
  noti-service/build.gradle
  noti-service/src/test/java/com/waither/notiservice/service/KafkaServiceTest.java
Labels: test

#28 ✨ feat: 알림 서비스 구체화 (#23)
  noti-service/src/main/java/com/waither/notiservice/NotiServiceApplication.java
  noti-service/src/main/java/com/waither/notiservice/api/NotificationController.java
  noti-service/src/main/java/com/waither/notiservice/config/RedisConfig.java
  noti-service/src/main/java/com/waither/notiservice/domain/FireBaseToken.java
  noti-service/src/main/java/com/waither/notiservice/domain/UserData.java
  noti-service/src/main/java/com/waither/notiservice/domain/UserMedian.java
  noti-service/src/main/java/com/waither/notiservice/dto/kafka/TokenDto.java
  noti-service/src/main/java/com/waither/notiservice/dto/kafka/UserMedianDto.java
  noti-service/src/main/java/com/waither/notiservice/dto/kafka/UserSettingsDto.java
  noti-service/src/main/java/com/waither/notiservice/enums/Expressions.java
  noti-service/src/main/java/com/waither/notiservice/redis/FireTokenBaseRepository.java
  noti-service/src/main/java/com/waither/notiservice/repository/NotificationRepository.java
  noti-service/src/main/java/com/waither/notiservice/repository/UserMedianRepository.java
  noti-service/src/main/java/com/waither/notiservice/service/KafkaConsumer.java
  noti-service/src/main/java/com/waither/notiservice/service/NotificationService.java
  noti-service/src/main/resources/bootstrap.yml
  noti-service/src/test/java/com/waither/notiservice/service/KafkaConsumerTest.java
  noti-service/src/test/java/com/waither/notiservice/service/NotificationServiceTest.java
Labels: feat

#29 ✨ feat: 좌표 <-> 위도, 경도 변환 로직 구현
  weather-service/build.gradle
  weather-service/src/main/java/com/waither/weatherservice/gps/GpsTransfer.java
  weather-service/src/main/java/com/waither/weatherservice/gps/LatXLngY.java
  weather-service/src/main/java/com/waither/weatherservice/openapi/OpenApiUtil.java
  weather-service/src/test/java/com/waither/weatherservice/GpsTransferTest.java
Labels: feat

#36 ✨ feat: Redis 환경 기능 개선 + 상시 위치 정보 알림 API 구현 (#30)
  noti-service/src/main/java/com/waither/notiservice/api/NotificationController.java
  noti-service/src/main/java/com/waither/notiservice/domain/UserData.java
  noti-service/src/main/java/com/waither/notiservice/dto/LocationDto.java
  noti-service/src/main/java/com/waither/notiservice/redis/FireTokenBaseRepository.java
  noti-service/src/main/java/com/waither/notiservice/service/KafkaConsumer.java
  noti-service/src/main/java/com/waither/notiservice/service/NotificationService.java
  noti-service/src/main/java/com/waither/notiservice/utils/RedisUtils.java
  noti-service/src/test/java/com/waither/notiservice/service/KafkaConsumerTest.java
Labels: feat, refactor
