Repository WaitherTeam/Waither-BE, pull requests merged in 2024-05, with the labels that each got.

#40 ✨ feat: 사용자 설정 API (#33)
  Eureka/.gitignore
  apiGateway-service/.gitignore
  apiGateway-service/src/main/java/com/waither/apigatewayservice/util/SeverHttpResponseUtil.java
  config-service/.gitignore
  noti-service/.gitignore
  user-service/.gitignore
  user-service/build.gradle
  user-service/src/main/java/com/waither/userservice/config/WebMvcConfig.java
  user-service/src/main/java/com/waither/userservice/controller/AccountsController.java
  user-service/src/main/java/com/waither/userservice/controller/SettingController.java
  user-service/src/main/java/com/waither/userservice/dto/EmailVerificationDto.java
  user-service/src/main/java/com/waither/userservice/dto/LoginRequestDto.java
  user-service/src/main/java/com/waither/userservice/dto/RegisterRequestDto.java
  user-service/src/main/java/com/waither/userservice/dto/converter/AccountConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/AccountReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/request/SettingReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/response/AccountResDto.java
  user-service/src/main/java/com/waither/userservice/dto/response/SettingResDto.java
  user-service/src/main/java/com/waither/userservice/entity/Setting.java
  user-service/src/main/java/com/waither/userservice/entity/Settings.java
  user-service/src/main/java/com/waither/userservice/entity/User.java
  user-service/src/main/java/com/waither/userservice/entity/UserData.java
  user-service/src/main/java/com/waither/userservice/global/annotation/AuthUser.java
  user-service/src/main/java/com/waither/userservice/global/annotation/AuthUserArgumentResolver.java
  user-service/src/main/java/com/waither/userservice/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/waither/userservice/global/response/ErrorCode.java
  user-service/src/main/java/com/waither/userservice/jwt/filter/JwtAuthenticationFilter.java
  user-service/src/main/java/com/waither/userservice/jwt/util/JwtUtil.java
  user-service/src/main/java/com/waither/userservice/repository/SettingRepository.java
  user-service/src/main/java/com/waither/userservice/repository/UserRepository.java
  user-service/src/main/java/com/waither/userservice/service/AccountsService.java
  user-service/src/main/java/com/waither/userservice/service/EmailService.java
  user-service/src/main/java/com/waither/userservice/service/SettingService.java
  user-service/src/main/resources/templates/authEmail.html
  user-service/src/main/resources/templates/tempPasswordEmail.html
  weather-service/.gitignore
Labels: feat

#43 ✨ feat: API 응답 정규화 (#37)
  noti-service/src/main/java/com/waither/notiservice/api/NotificationController.java
  noti-service/src/main/java/com/waither/notiservice/api/request/LocationDto.java
  noti-service/src/main/java/com/waither/notiservice/dto/LocationDto.java
  noti-service/src/main/java/com/waither/notiservice/global/exception/CustomException.java
  noti-service/src/main/java/com/waither/notiservice/global/exception/GlobalExceptionHandler.java
  noti-service/src/main/java/com/waither/notiservice/global/response/ApiResponse.java
  noti-service/src/main/java/com/waither/notiservice/global/response/ErrorCode.java
  noti-service/src/main/java/com/waither/notiservice/global/response/status/BaseErrorCode.java
  noti-service/src/main/java/com/waither/notiservice/service/KafkaConsumer.java
  noti-service/src/main/java/com/waither/notiservice/service/NotificationService.java
Labels: feat

#47 ✨ feat: 사용자 설정 API GET 기능 (#41)
  user-service/src/main/java/com/waither/userservice/controller/AccountsController.java
  user-service/src/main/java/com/waither/userservice/controller/SettingController.java
  user-service/src/main/java/com/waither/userservice/dto/converter/AccountConverter.java
  user-service/src/main/java/com/waither/userservice/dto/converter/SettingConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/AccountReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/request/SettingReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/response/SettingResDto.java
  user-service/src/main/java/com/waither/userservice/entity/Region.java
  user-service/src/main/java/com/waither/userservice/entity/Setting.java
  user-service/src/main/java/com/waither/userservice/entity/User.java
  user-service/src/main/java/com/waither/userservice/repository/RegionRepository.java
  user-service/src/main/java/com/waither/userservice/repository/SurveyRepository.java
  user-service/src/main/java/com/waither/userservice/repository/UserDataRepository.java
  user-service/src/main/java/com/waither/userservice/repository/UserMedianRepository.java
  user-service/src/main/java/com/waither/userservice/service/AccountsService.java
  user-service/src/main/java/com/waither/userservice/service/EmailService.java
  user-service/src/main/java/com/waither/userservice/service/QueryService/SettingQueryService.java
  user-service/src/main/java/com/waither/userservice/service/SettingService.java
Labels: feat

#49 📝 docs: API 문서 통합화 (#44)
  .github/workflows/apiDocs.yml
  noti-service/build.gradle
  noti-service/docs/noti.json
Labels: documentation

#54 📝 docs: api json 추가
  user-service/build.gradle
  user-service/docs/user.json
  user-service/src/main/java/com/waither/userservice/controller/SettingController.java
  user-service/src/main/java/com/waither/userservice/controller/UserController.java
  user-service/src/main/java/com/waither/userservice/dto/converter/UserConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/SettingReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/request/UserReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/response/UserResDto.java
  user-service/src/main/java/com/waither/userservice/jwt/filter/JwtAuthenticationFilter.java
  user-service/src/main/java/com/waither/userservice/service/SettingService.java
  user-service/src/main/java/com/waither/userservice/service/UserService.java
  user-service/src/main/resources/bootstrap.yml
Labels: documentation

#57 📝 docs : API 문서 통합
  .github/workflows/apiDocs.yml
Labels: documentation

#62 💚 ci/cd: 배포 환경 구축 (#61)
  .github/workflows/apiDocs.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Eureka/Dockerfile
  Eureka/build.gradle
  apiGateway-service/Dockerfile
  apiGateway-service/build.gradle
  apiGateway-service/src/main/java/com/waither/apigatewayservice/ApiGatewayServiceApplication.java
  apiGateway-service/src/main/resources/bootstrap.yml
  config-service/Dockerfile
  config-service/build.gradle
  config-service/src/main/resources/bootstrap.yml
  docker-compose.yml
  noti-service/Dockerfile
  noti-service/build.gradle
  script/common.sh
  script/deploy.sh
  script/docker_init.sh
  user-service/Dockerfile
  user-service/build.gradle
  weather-service/Dockerfile
  weather-service/build.gradle
Labels: ci, cd

#63 ♻️ refactor: 설문조사 내부 로직 수정 (#59)
  user-service/build.gradle
  user-service/src/main/java/com/waither/userservice/controller/SettingController.java
  user-service/src/main/java/com/waither/userservice/controller/SurveyController.java
  user-service/src/main/java/com/waither/userservice/converter/RegionConverter.java
  user-service/src/main/java/com/waither/userservice/converter/SettingConverter.java
  user-service/src/main/java/com/waither/userservice/converter/SurveyConverter.java
  user-service/src/main/java/com/waither/userservice/converter/UserConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/SettingReqDto.java
  user-service/src/main/java/com/waither/userservice/dto/response/SettingResDto.java
  user-service/src/main/java/com/waither/userservice/entity/Setting.java
  user-service/src/main/java/com/waither/userservice/entity/Survey.java
  user-service/src/main/java/com/waither/userservice/entity/User.java
  user-service/src/main/java/com/waither/userservice/entity/UserData.java
  user-service/src/main/java/com/waither/userservice/entity/UserMedian.java
  user-service/src/main/java/com/waither/userservice/entity/enums/Season.java
  user-service/src/main/java/com/waither/userservice/entity/enums/UserStatus.java
  user-service/src/main/java/com/waither/userservice/global/jwt/userdetails/PrincipalDetailsService.java
  user-service/src/main/java/com/waither/userservice/global/response/ErrorCode.java
  user-service/src/main/java/com/waither/userservice/repository/UserDataRepository.java
  user-service/src/main/java/com/waither/userservice/repository/UserMedianRepository.java
  user-service/src/main/java/com/waither/userservice/service/commandService/SettingService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/SurveyService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/UserService.java
  user-service/src/main/java/com/waither/userservice/service/queryService/SettingQueryService.java
  user-service/src/main/java/com/waither/userservice/service/queryService/SurveyQueryService.java
  user-service/src/main/java/com/waither/userservice/util/CalculateUtil.java
Labels: refactor

#80 📝 docs: CI/CD 스크립트 수정
  .github/workflows/cd.yml
  apiGateway-service/src/main/resources/bootstrap.yml
  config-service/src/main/resources/bootstrap.yml
  docker-compose.yml
  noti-service/src/main/resources/bootstrap.yml
  script/common.sh
  script/deploy.sh
  user-service/src/main/resources/bootstrap.yml
  weather-service/src/main/resources/bootstrap.yml
Labels: documentation, ci, cd

#82 📝 docs: Swagger 적용 (#77)
  apiGateway-service/Dockerfile
  apiGateway-service/build.gradle
  apiGateway-service/src/main/resources/bootstrap.yml
  noti-service/build.gradle
  noti-service/src/main/resources/bootstrap.yml
  user-service/src/main/resources/bootstrap.yml
  weather-service/src/main/resources/bootstrap.yml
Labels: documentation

#88 feat: 카프카 설정 및 사용자 설정 정보값 / Median 테이블 전송 (#81)
  user-service/.gitignore
  user-service/build.gradle
  user-service/docker-compose.yml
  user-service/src/main/java/com/waither/userservice/config/CorsConfig.java
  user-service/src/main/java/com/waither/userservice/config/SecurityConfig.java
  user-service/src/main/java/com/waither/userservice/controller/UserController.java
  user-service/src/main/java/com/waither/userservice/converter/SurveyConverter.java
  user-service/src/main/java/com/waither/userservice/dto/request/SurveyReqDto.java
  user-service/src/main/java/com/waither/userservice/entity/Setting.java
  user-service/src/main/java/com/waither/userservice/entity/UserMedian.java
  user-service/src/main/java/com/waither/userservice/global/jwt/filter/JwtAuthorizationFilter.java
  user-service/src/main/java/com/waither/userservice/global/util/CalculateUtil.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaConfig.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaConsumer.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaConverter.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaDto.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaProducer.java
  user-service/src/main/java/com/waither/userservice/kafka/KafkaService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/SettingService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/SurveyService.java
  user-service/src/main/java/com/waither/userservice/service/commandService/UserService.java
  user-service/src/main/resources/application-secret.yml
  user-service/src/main/resources/application.yml
Labels: feat, refactor

#96 ♻️refactor: 지역 엔티티 수정 및 스케줄링 수정
  weather-service/src/main/java/com/waither/weatherservice/controller/WeatherTestController.java
  weather-service/src/main/java/com/waither/weatherservice/entity/Region.java
  weather-service/src/main/java/com/waither/weatherservice/repository/RegionRepository.java
  weather-service/src/main/java/com/waither/weatherservice/response/ErrorCode.java
  weather-service/src/main/java/com/waither/weatherservice/response/WeatherErrorCode.java
  weather-service/src/main/java/com/waither/weatherservice/scheduler/SchedulerConfig.java
  weather-service/src/main/java/com/waither/weatherservice/service/WeatherService.java
  weather-service/src/main/resources/api/region.sql
  weather-service/src/main/resources/api/regionV2.sql
Labels: refactor
